steps:
  # Build the Docker image with two tags
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/$_SERVICE_NAME:$SHORT_SHA
      - -t
      - gcr.io/$PROJECT_ID/$_SERVICE_NAME:latest
      - .

  # Push both image tags to Container Registry
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/$PROJECT_ID/$_SERVICE_NAME:$SHORT_SHA

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/$PROJECT_ID/$_SERVICE_NAME:latest

  # Deploy to Cloud Run (fully managed)
  - name: gcr.io/cloud-builders/gcloud
    args:
      - run
      - deploy
      - $_SERVICE_NAME
      - --image
      - gcr.io/$PROJECT_ID/$_SERVICE_NAME:$SHORT_SHA
      - --platform
      - managed
      - --region
      - $_REGION
      - --allow-unauthenticated

# Substitutions for service name and region
substitutions:
  _SERVICE_NAME: trigger-test
  _REGION: us-central1

# List the images that this build produces
images:
  - gcr.io/$PROJECT_ID/$_SERVICE_NAME:$SHORT_SHA
  - gcr.io/$PROJECT_ID/$_SERVICE_NAME:latest

# Build options with logging
options:
  logging: CLOUD_LOGGING_ONLY

# Build timeout
timeout: '1200s'
